version: '2.2'

services:
  samba-video:
    build: .
    image: ismael49/samba:v1
    volumes:
      - ./conf/smb.conf:/etc/samba/smb.conf:ro
      - /data/videotheque:/data/videotheque:ro
    networks:
      samba_net:
        ipv4_address: 192.168.2.10

networks:
  samba_net:
    ipam:
      config:
        - subnet: 192.168.2.0/24

