version: '2.2'

services:
  samba-video:
    build: .
    image: ismael49/samba:v1
    volumes:
      - ./conf/smb.conf:/etc/samba/smb.conf:ro
      - /data/videotheque:/data/videotheque:ro
    networks:
      - samba_net

networks:
  samba_net:
    ipam:
      config:
        - subnet: 192.168.2.0/24
          aux_addresses: 
            samba-video: 192.168.2.2

