version: '2.2'

services:
  samba-video:
    build: .
    image: ismael49/samba:v2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_CONF_NAME=freyja
    volumes:
      - ./conf/smb.conf:/etc/samba/smb.conf:ro
      - ./conf/freyja.conf:/etc/wireguard/freyja.conf:ro
      - /data/videotheque:/data/videotheque:ro
    networks:
      samba_net:
        ipv4_address: 192.168.2.10

networks:
  samba_net:
    ipam:
      config:
        - subnet: 192.168.2.0/24

